### ISSUE TITLE
Can't understand some fields

### ISSUE THREAD

**Issue by g4s8** [yegor256/0rsk#30]
I can't understand some fields when creating new "cause", "risk", "effect", it's 3 gray fields and 1 fields with prepared emoji. I think some kind of hint is needed here:
![scrot-2019-05-14-12:00:52](https://user-images.githubusercontent.com/1524988/57685755-3d01f100-7641-11e9-9a81-c6e1f3a07c6c.png)

**Comment by yegor256** [comment]
@rultor release, tag is `0.6.3`

**Comment by yegor256** [comment]
@g4s8 This problem is already fixed, I believe. However, if you see it again, please don't hesitate to create a new issue. Thanks for your contribution!

**Comment by g4s8** [comment]
@yegor256 thanks
