### ISSUE TITLE
Telegram bot is not working

### ISSUE THREAD

**Issue by g4s8** [yegor256/0rsk#31]
`@zerorsk_bot` is not responding for any message, I tried some predefined commands like `/done` and `/tasks` but it's keeping silence. (also tried hello and version - no response)

**Comment by yegor256** [comment]
@g4s8 hm... works for me. Can you try now?

**Comment by g4s8** [comment]
@yegor256 yes, it's working now. Also, I received answers for yesterday messages (with 1 day delay).
