### ISSUE TITLE
Empty notifications from telegram bot every few minutes

### ISSUE THREAD

**Issue by g4s8** [yegor256/0rsk#40]
Telegram bot is sending me empty notifications every few minutes. I'm not sure, but it may be related: I deleted some test causes and risks before that.
![scrot-2019-05-21-12:59:16](https://user-images.githubusercontent.com/1524988/58087219-cdec4580-7bc8-11e9-861a-31fbaea7f65d.png)

**Comment by yegor256** [comment]
@rultor release, tag is `0.6.10`

**Comment by yegor256** [comment]
@rultor release, tag is `0.6.11`

**Comment by yegor256** [comment]
@g4s8 should be OK now, sorry about it
