### ISSUE TITLE
Ability to delete a project

### ISSUE THREAD

**Issue by agorlov** [yegor256/0rsk#41]
To start I created a first project, but now I want to get rid of it.

Delete or archive it.

**Comment by yegor256** [comment]
@rultor release, tag is `0.6.12`

**Comment by yegor256** [comment]
@rultor release, tag is `0.6.13`

**Comment by yegor256** [comment]
@agorlov should work

**Comment by agorlov** [comment]
@yegor256 I confirm, it works. Thank you.
