### ISSUE TITLE
Mark a task which can not be performed, without deleting it

### ISSUE THREAD

**Issue by Apocryphe** [yegor256/0rsk#46]
After listing my tasks, it can happen someone could not be done.

In this case, I dont want to delete them because I want to keep track it can't be a solution, to force me to create different one.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@apocryphe[/z](https://www.0crat.com/u/apocryphe) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RFVLU72) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@Apocryphe what do you want to do with them?

**Comment by Apocryphe** [comment]
Keep them :
- to know what have already been tried
- to be able to re-activate them if new event/context allow it

**Comment by yegor256** [comment]
@Apocryphe you just need to set a repetitive schedule for your plan, like `weekly` or `monthly`. In this case the task will be created over and over again. One-time plans are supposed to die after they are "done". This is the idea.

Or you mean you want to see the archive of closed plans?

**Comment by Apocryphe** [comment]
I see your point. I will try to use your tool in this way.

Thx for your job.

*Florent DOTTO*

C.T.O.

(+33) (0)6 47 63 17 33

Brennus Analytics


Le mar. 9 juil. 2019 à 07:20, Yegor Bugayenko <notifications@github.com> a
écrit :

**Comment by yegor256** [comment]
@rultor release, tag is `0.7.0`

**Comment by yegor256** [comment]
@Apocryphe I added a new feature. You can now postpone a task without deleting it. Hope, this helps. Well, it helps me)

**Comment by 0crat** [comment]
Job `gh:yegor256/0rsk#46` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
