### ISSUE TITLE
How to create a Risk with same Cause related to multiple Effects and Results ?

### ISSUE THREAD

**Issue by Apocryphe** [yegor256/0rsk#51]
Hello yegor,

I want to create something like (C, E1, R1) and (C,E2,R2).

I've already created (C, E1, R1).

First - I try to create a new Risk from scratch with C, E2, R2 => internal error "C already exists."

Second - I try to use Edit on (C, E1, R1) and replacing E1 with E2 and R1 with R2 => My initial Risk with just modified, no surprise... (losing E1 and R1).

How can I do ?

Thx.

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@apocryphe[/z](https://www.0crat.com/u/apocryphe) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RFVLU72) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@Apocryphe you should click "Detach" when you do the editing.

**Comment by 0crat** [comment]
Job `gh:yegor256/0rsk#51` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
